### ISSUE TITLE
Issue encountered when deploying develompent site to Cloudfoundry

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1033]
Hi there! 👋 Was trying to deploy the development site to IBM Cloud and came across this issue when it was trying to stage:

```
2018-08-15T16:53:34.57-0500 [APP/PROC/WEB/0] OUT > carbon-components@7.2.1 start /home/vcap/app
2018-08-15T16:53:34.57-0500 [APP/PROC/WEB/0] OUT > node server.js
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR fs.js:640
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR                  ^
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR Error: ENOENT: no such file or directory, open '/home/vcap/app/node_modules/browser-sync-ui/templates/plugin.tmpl'
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Error (native)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Object.fs.openSync (fs.js:640:18)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Object.fs.readFileSync (fs.js:508:33)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at templateFile (/home/vcap/app/node_modules/browser-sync-ui/lib/hooks.js:11:15)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/node_modules/browser-sync-ui/lib/hooks.js:4:22)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:570:32)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:579:10)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Module.load (module.js:487:32)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:446:12)
2018-08-15T16:53:35.35-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:438:3)
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-109-generic
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! node v6.9.0
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! npm  v3.10.8
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! carbon-components@7.2.1 start: `node server.js`
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR!
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Failed at the carbon-components@7.2.1 start script 'node server.js'.
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! If you do, this is most likely a problem with the carbon-components package,
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR!     node server.js
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs carbon-components
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls carbon-components
2018-08-15T16:53:35.37-0500 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
2018-08-15T16:53:35.38-0500 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
2018-08-15T16:53:35.38-0500 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log
```

Wanted to make this issue real quick to capture this and provide an issue for folks to PR off of for a fix 👍

**Comment by joshblack** [comment]
cc @asudoh
