### ISSUE TITLE
Error on close - ModalWrapper

### ISSUE THREAD

**Issue by camilascalzo** [carbon-design-system/carbon#12061]
Uncaught TypeError: Cannot read properties of undefined (reading 'current')
    at ModalWrapper.js:48:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    
    I checked and the same issue is reflected in the guidance when trying to close
    https://carbondesignsystem.com/components/modal/usage/

**Comment by tay1orjones** [comment]
Thanks for reporting this @camilascalzo, this should be fixed by https://github.com/carbon-design-system/carbon/pull/11839
