### ISSUE TITLE
[Question]: <cds-overflowmenu> not functioning as expected when server side rendering is enabled.

### ISSUE THREAD

**Issue by alantao912** [carbon-design-system/carbon#16654]
### Question for Carbon

I am trying to use <cds-overflow-menu> on the frontend of my application. It renders fine, but when I try to click on it, I get the following error:

Error:

```
ERROR ReferenceError: document is not defined
    at DocumentService (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/carbon-components-angular/fesm2020/carbon-components-angular-utils.mjs:321:24)
    at Object.DocumentService_Factory (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/carbon-components-angular/fesm2020/carbon-components-angular-utils.mjs:344:10)
    at eval (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:3219:47)
    at runInInjectorProfilerContext (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:866:9)
    at R3Injector.hydrate (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:3218:21)
    at R3Injector.get (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:3082:33)
    at injectInjectorOnly (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:1100:40)
    at Module.ɵɵinject (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:1106:42)
    at Object.EventService_Factory (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/carbon-components-angular/fesm2020/carbon-components-angular-utils.mjs:380:37)
    at eval (/mnt/c/users/alant/Desktop/Education/Projects/Resumax/frontend/node_modules/@angular/core/fesm2022/core.mjs:3219:47)
```

HTML Below:
```
<cds-overflow-menu>
                <cds-overflow-menu-option> Option 1 </cds-overflow-menu-option>
</cds-overflow-menu>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by guidari** [comment]
Hey @alantao912 
This is in our radar and might be solved in this [PR](https://github.com/carbon-design-system/carbon/pull/16559)

**Comment by alantao912** [comment]
Thank you @guidari !
