### ISSUE TITLE
This seems to be broken!

### ISSUE THREAD

**Issue by sabsaxo** [carbon-design-system/carbon#507]
After git clone, npm install and npm run dev yadda yadda, this is what we get:

```
WARNING: 
REASON: Accessing the `card` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `detail-page-header` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `module` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `interior-left-nav` component from the `carbon-components`package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `order-summary` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
Backtrace:
	src/globals/scss/styles.scss:114

[09:37:46] 'scripts:dev' errored after 2.2 s
[09:37:46] SyntaxError: ... /src/components/checkbox/checkbox.js: Unexpected token (124:20)

...

[09:37:46] Finished 'sass:dev' after 2.99 s
```

Not the greatest of experiences. Any way to fix this?

**Comment by marijohannessen** [comment]
Hi @sabsaxo ! I'm sorry to hear that you're experiencing problems! I think we need a little bit more information in order to debug this. I just tried cloning the repo from scratch, ran `yarn` and then `npm run dev` and it runs fine 🤔  I'm using Node v6.10.2. Which node version are you on?

**Comment by marijohannessen** [comment]
Also - the first part of the error message is just some warnings that we've moved some components to an [add-ons repo](https://github.com/carbon-design-system/carbon-addons-bluemix) instead of the main repo. We're not removing them from this repo just yet though, so until then the warnings will show up, unfortunately.

**Comment by sabsaxo** [comment]
Sorry, skipped the project in favor of another, as this seemed to be way to much hassle to get not even working. Having this experience (see below) and then having a http://localhost:3000 with the eternal spinner of death and a page title of »Problem loading page« ... and that only after waiting for this: Done in 298.65s. (when running: $ yarn)!

I think you've over complicated things by running yarn over npm for a start. And from there the thing starts falling apart ...

```
$ npm run dev

> carbon-components@7.2.1 dev /Applications/MAMP/htdocs/carbon-components
> gulp serve & npm run serve


> carbon-components@7.2.1 serve /Applications/MAMP/htdocs/carbon-components
> nodemon -e dust,js server.js

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server.js
[nodemon] starting `node server.js`
/Applications/MAMP/htdocs/carbon-components/node_modules/freshy/index.js:54
    if (require.cache.hasOwnProperty(path) && require.cache[path].children) {
                      ^

TypeError: require.cache.hasOwnProperty is not a function
    at unload (/Applications/MAMP/htdocs/carbon-components/node_modules/freshy/index.js:54:23)
    at getFresh (/Applications/MAMP/htdocs/carbon-components/node_modules/freshy/index.js:20:5)
    at /Applications/MAMP/htdocs/carbon-components/node_modules/freshy/index.js:94:19
    at exports.create (/Applications/MAMP/htdocs/carbon-components/node_modules/adaro/lib/engine.js:43:16)
    at Object.<anonymous> (/Applications/MAMP/htdocs/carbon-components/server.js:18:26)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
[nodemon] app crashed - waiting for file changes before starting...
[10:15:52] Using gulpfile /Applications/MAMP/htdocs/carbon-components/gulpfile.js
[10:15:52] Starting 'sass:dev'...
[10:15:52] Starting 'scripts:dev'...
[10:15:52] Starting 'watch'...
[10:15:52] Finished 'watch' after 458 ms
WARNING: 
REASON: Accessing the `card` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `detail-page-header` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `module` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `interior-left-nav` component from the `carbon-components`package is deprecated. Use the `carbon-addons-bluemix` package instead.
REASON: Accessing the `order-summary` component from the `carbon-components` package is deprecated. Use the `carbon-addons-bluemix` package instead.
Backtrace:
	src/globals/scss/styles.scss:115

[10:15:54] Finished 'sass:dev' after 2.35 s
[10:15:57] Finished 'scripts:dev' after 5.47 s
[10:15:57] Starting 'build:dev'...
[10:15:57] Finished 'build:dev' after 31 μs
[10:15:57] Starting 'browser-sync'...
[10:15:57] Finished 'browser-sync' after 29 ms
[10:15:57] Starting 'serve'...
[10:15:57] Finished 'serve' after 2.76 μs
[Carbon Components] [info] Proxying: http://localhost:8080
[Carbon Components] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.20.122:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.20.122:3001
 ---------------------------------------
```

**Comment by asudoh** [comment]
@sabsaxo For the record - The vanilla version as of today doesn’t have preference wrt Yarn over NPM. That said, you can simply do:

```sh
> npm install
> npm run serve
```

You may want to try `rm -Rf node_modules` beforehand, to make sure things that Yarn may have messed around with are cleaned up. Hope this helps.
