### ISSUE TITLE
Sketch icon `generate` script cannot handle icon range subsets

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#5582]
## What package(s) are you using?

`@carbon/sketch`

## Detailed description

> Describe in detail the issue you're having.

when trying to generate a subset of icons for an icon page, the command will fail with the message `An error occured, please check the development logs`

the development log shows

```sh
$ skpm log -f
    at __skpm_run@[native code] (/)
'[Carbon Elements] commands/icons/generate: Done in 30ms'
TypeError: undefined is not an object (evaluating 'symbol.createNewInstance')
    at _loop (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16228:38)
    at /Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16242:22
    at command (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16093:7)
    at generate (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16144:59)
    at __skpm_run (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:17968:19)
    at __skpm_run@[native code] (/)
'[Carbon Elements] commands/icons/generate: Done in 40ms'
```

## Steps to reproduce the issue

1. modify `carbon/packages/sketch/src/commands/icons/shared.js` to only deal with a subset of icons (either modify the `start` and `end` variables to be a subset of the full icons list or directly change the slice size in `symbolsToSync`)
2. `yarn build`
3. sync and generate the icons in Sketch

**Comment by joshblack** [comment]
I think this issue should address adding an error if a symbol does not exist. For context, we want to run sync before generate and should error out if a symbol has not been generated as it is a sign that the sync script did not execute correctly 👍
