### ISSUE TITLE
IE11: Overflow menu does not show the menu items when clicking on the Overflow menu icon

### ISSUE THREAD

**Issue by bjakob01** [carbon-design-system/carbon#942]
## Detailed description

With Internet Explorer 11, the overflow menu does not show the menu items when clocking on the overflow menu icon. 
We are using Angular 6 and the polyfills.ts file imports all polyfills needed by Angular.

Browser version:
Internet Explorer 11
Version: 11.0.9600.19035CO
Update Versions: 11.0.65 (KB4230450)
Product ID: 00150-20000-00003-AA459

In the IE Developer tool I can see thee following:
When changing the state of the option menu to „shown“, an error will be thrown:

2018-06-28T05:42:50.723Z ERROR  TypeError: Object doesn't support this action   
at changeState (http://localhost:4200/vendor.js:71580:9)   
at changeState (http://localhost:4200/vendor.js:67992:7)   
at _handleDocumentClick (http://localhost:4200/vendor.js:68020:7)   
at Anonymous function (http://localhost:4200/vendor.js:67948:7)   
at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:7464:13)   
at onInvokeTask (http://localhost:4200/vendor.js:35796:17)   
at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:7464:13)   
at Zone.prototype.runTask (http://localhost:4200/polyfills.js:7233:21)   
at ZoneTask.invokeTask (http://localhost:4200/polyfills.js:7541:17)   
at invokeTask (http://localhost:4200/polyfills.js:8585:9)

> What version of the Carbon Design System are you using? 
    "carbon-addons-cloud": "^2.1.0",
    "carbon-addons-cloud-vanilla": "^1.0.0",
    "carbon-components": "^9.0.14",
    "carbon-icons": "^7.0.7",

## Steps to reproduce the issue
By the way, the Overflow menu does also not work for CodePen and IE11

1. open IE11
2. navigate to URL https://codepen.io/team/carbon/pen/MOEwjp
3. click on Overflow menu icon (three dots)

### Expected result
Overflow menu items will be shown

### Actual result
nothing happens ... nothing will be shown

**Comment by asudoh** [comment]
Hi @bjakob01 thank you for reporting - It appears that your CodePen missing `Object.assign()` polyfill (and possibly other polyfills)? Would you fix it...? Thanks!

**Comment by bjakob01** [comment]
I installed and imported the [mdn-polyfills](https://github.com/msn0/mdn-polyfills).  Now, the Overflow menus are working fine.

@asudoh Thank you for your help
