### ISSUE TITLE
Data table V2: Escape key in Search field throws: TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by StefanDoersam** [carbon-design-system/carbon#967]
After the following issue is closed
Data table V2: Escape key event handler calls undefined method #674
https://github.com/IBM/carbon-components/issues/674.

now a new exception is thrown
TypeError: Cannot read property 'dataset' of null
scripts.js:3583
    at DataTableV2._actionBarToggle (http://localhost:4200/scripts.js:3583:28)
    at DataTableV2._actionBarCancel (http://localhost:4200/scripts.js:3562:12)
    at HTMLDivElement._keydownHandler (http://localhost:4200/scripts.js:3641:14)
    at ZoneDelegate.push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:7778:31)
    at Zone.push.../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:7545:47)
    at ZoneTask.push.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:7853:34)
    at invokeTask (http://localhost:4200/polyfills.js:8897:14)
    at HTMLDivElement.globalZoneAwareCallback (http://localhost:4200/polyfills.js:8934:21)

Used carbon-comonents: 9.1.16

Whenever the escape is is pressed in a search entry field the above exception is thrown.
Place the cursor within the Search filed and press the ESC key.

![image](https://user-images.githubusercontent.com/34157485/42630415-ef7483b8-85d6-11e8-98a7-9a5b4029efa3.png)

**Comment by tw15egan** [comment]
Seems like the fix made in #674 assumes there will be an action bar, which is not the case in the expandable data-table. Pushing up a fix now

**Comment by StefanDoersam** [comment]
Many Thanks! Works fine now.
